# Generated by Django 4.1 on 2022-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_photocard_qr_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='music_list',
        ),
        migrations.RemoveField(
            model_name='albumfrime',
            name='music_list',
        ),
        migrations.AddField(
            model_name='album',
            name='music_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='albumfrime',
            name='music_list',
            field=models.TextField(null=True),
        ),
    ]
