# Generated by Django 4.1 on 2022-08-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0008_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='album_image',
            field=models.ImageField(blank=True, null=True, upload_to='sang_album_img'),
        ),
        migrations.AddField(
            model_name='count',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='album.artist'),
            preserve_default=False,
        ),
    ]
