# Generated by Django 4.0.5 on 2022-08-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0012_remove_album_music_list_album_artist_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albumfrime',
            name='album_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='logo_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='count',
            name='album_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photocard',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photocardfrime',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
